"""
Learned SQL Templates - Auto-generated by Query Learning System
================================================================
DO NOT EDIT MANUALLY - This file is auto-generated from successful
dynamically generated queries that have been promoted to permanent templates.

These queries were learned from user interactions and have proven
reliable through multiple successful executions.

Last updated: 2026-02-10T00:00:00
Total templates: 0
"""

# Initial empty templates dict - will be populated by the learning system
TEMPLATES = {}

# Example of what a learned template looks like:
# TEMPLATES = {
#     "LEARNED_A1B2C3D4": {
#         "id": "LEARNED_A1B2C3D4",
#         "intents": ["COUNT"],
#         "question_en": "What are the health certificates?",
#         "question_ar": "",
#         "default_chart": "bar",
#         "sql": "SELECT ... FROM ...",
#         "filters": {},
#         "learned": True,
#         "learned_at": "2026-02-10T12:00:00",
#         "use_count": 5,
#         "success_rate": 1.0
#     }
# }
